#!/bin/bash

export DOTFILES=$HOME/.dotfiles


main() {
  set -e

  if [ -z $nosudo ]
  then
    sudo -v -p "Enter sudo password (or run with --nosudo):"

    $DOTFILES/script/install
    set_default_shell
  fi

  setup_gitconfig
  install_dotfiles

  if [ "$(uname -s)" == "Darwin" ]
  then
    setup_solarized_for_mac
  fi

  sudo -k
  echo '  Setup complete!'
}


info() {
  printf "\r  [ \033[00;34m...\033[0m ] $1\n"
}

user() {
  printf "\r  [  \033[0;33m?\033[0m  ] $1 "
}

success() {
  printf "\r\033[2K  [ \033[00;32mOK \033[0m ] $1\n"
}

error() {
  printf "\r\033[2K  [\033[0;31mERROR\033[0m] $1\n"
}

fail() {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}

set_default_shell() {
  info "Setting zsh as default shell..."

  if [ ! -f /bin/zsh ]
  then
    user "You don't have zsh. Download and install zsh? [y/n]"
    read -n 1 first

    while [ $first != "y" ] && [ $first != "Y" ] && [ $first != "n" ] && [ $first != "N" ]
    do
      user "Please answer [y]es or [n]o:"
      read -n 1 first
    done

    if [ $first == "y" ] || [ $first == "Y" ]
    then
      info "Installing zsh..."
      if [ "$(uname -s)" == "Linux" ]
      then
        sudo apt-get install zsh --yes 1>/dev/null 2>/dev/null
      fi
      success "zsh installed"
    fi
  fi

  if [ -f /bin/zsh ]
  then
    sudo chsh -s /bin/zsh `whoami` 1>/dev/null 2>/dev/null
    success "Set zsh as default shell"
  else
    error "Did not set zsh as default shell"
  fi

  echo ''
}

setup_gitconfig() {
  OUTPUT_FILE=$DOTFILES/git/gitconfig.symlink
  TEMPLATE_FILE=$OUTPUT_FILE.template

  if [ ! -f $OUTPUT_FILE ]
  then

    info "Setting up gitconfig..."
    if [ -f $TEMPLATE_FILE ]
    then
      git_credential='cache'
      if [ "$(uname -s)" == "Darwin" ]
      then
        git_credential='osxkeychain'
      fi

      user ' - What is your github author name?'
      read -e git_authorname
      user ' - What is your github author email?'
      read -e git_authoremail

      sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" $TEMPLATE_FILE > $OUTPUT_FILE

      success 'gitconfig created'
    else
      error "Could not create gitconfig. Template file, $TEMPLATE_FILE, does not exist"
    fi
    echo ''
  fi
}

link_files() {
  ln -s $1 $2
  success "linked $1 to $2"
}

install_dotfiles() {
  info 'Installing dotfiles...'

  overwrite_all=false
  backup_all=false
  skip_all=false

  for source in `find -L $DOTFILES -maxdepth 2 -name \*.symlink`
  do
    dest="$HOME/.`basename \"${source/%.symlink/}\"`"   #this uses bash search and replace

    if [ -f $dest ] || [ -d $dest ]
    then

      overwrite=false
      backup=false
      skip=false

      if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]
      then
        user "File `basename $dest` already exists. What do you want to do? [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
        read -n 1 action

        case "$action" in
          o )
            overwrite=true;;
          O )
            overwrite_all=true;;
          b )
            backup=true;;
          B )
            backup_all=true;;
          s )
            skip=true;;
          S )
            skip_all=true;;
          * )
            ;;
        esac
      fi

      if [ "$overwrite" == "true" ] || [ "$overwrite_all" == "true" ]
      then
        rm -rf $dest
        success "removed $dest"
      fi

      if [ "$backup" == "true" ] || [ "$backup_all" == "true" ]
      then
        mv $dest $dest\.backup
        success "moved $dest to $dest.backup"
      fi

      if [ "$skip" == "false" ] && [ "$skip_all" == "false" ]
      then
        link_files $source $dest
      else
        success "skipped $source"
      fi

    else
      link_files $source $dest
    fi

  done

  echo ''
}

setup_solarized_for_mac() {
  if [ "$(uname -s)" != "Darwin" ]
  then
    return
  fi

  info "Setting up Terminal theme"
  $DOTFILES/osx/set_default_terminal_theme.sh
}


set_args() {
  while [ "$1" != "" ]; do
    case $1 in
      "-n" | "--nosudo")
        nosudo=true
        ;;
    esac
    shift
  done
}

set_args $*
main
